### ISSUE TITLE
claims aren't displayed anymore on works

### ISSUE THREAD

**Issue by thewholelifetolearn** [inventaire/inventaire-client#105]
I think that since the commit da7c51695008c67aece0749ed24ed3962f197248, the page to display information about a work doesn't show claim any more.  
Is it because I didn't add the argument `true` to the ordinal?

    {{claim claims 'wdt:P1545'}} {{!-- serie ordinal --}}

As an picture explains better then 1000 words, see below for screenshots

![image](https://user-images.githubusercontent.com/823564/27025651-88aab786-4f5b-11e7-83a3-b17755867912.png)

![image](https://user-images.githubusercontent.com/823564/27025668-9825cad4-4f5b-11e7-89b1-b6719adec840.png)

**Comment by maxlath** [comment]
@thewholelifetolearn the problem was on the handlebars claim helper: [`claim`](https://github.com/inventaire/inventaire-client/blob/b767383307a702b2814f130f19b255a783e3d74c/app/lib/handlebars_helpers/claims.coffee#L14-L19) should be used for properties where the value is another entity, while 'wdt:P1545' values are simple string, thus the error: in your example, the browser went looking for the entity corresponding to the URI `21`, instead of simply displaying `21` as a string value. That's what [`stringClaim`](https://github.com/inventaire/inventaire-client/blob/b767383307a702b2814f130f19b255a783e3d74c/app/lib/handlebars_helpers/claims.coffee#L44-L49) do.
My mistake, I should have spotted this issue while reviewing the PR :)
