### ISSUE TITLE
Allow unauthorized users to view an users public items

### ISSUE THREAD

**Issue by Abbe98** [inventaire/inventaire-client#17]
Currently requires that the user is logged in.

**Comment by maxlath** [comment]
for the moment, the access is limited for non-logged in users as it might require to handle the non-logged user cases for every piece of UI around: for instance, usually when you close a user inventory (clicking on the cross up-right in the side bar), you are redirected to the general inventory view with the list of your contacts and groups; where should a non-logged user be redirected?
So that's totally doable, just requires some time to be done well

**Comment by maxlath** [comment]
new requirement: public items should have the appropriate picture, title and description when shared on social networks

**Comment by maxlath** [comment]
the first part is done: making public books accessible to both logged in and non logged in users.
remaining: make the book's metadata appear when embedded in social networks

**Comment by maxlath** [comment]
and now it should all be working \o/
