### ISSUE TITLE
edition details mobile display on Firefox

### ISSUE THREAD

**Issue by jum-s** [inventaire/inventaire-client#170]
On small screens, display of edition box in firefox 60.5 is hidden (works on chromium)
I had trouble uploading an image but its seeable on [this page](https://inventaire.io/entity/inv:0a68df5f187729a463e3b74ee80f0b1a) with ff and a `ctrl+shift+m`

The monkey patch would be to delete the flex column display [`app/modules/entities/scss/_edition_li.scss`](https://github.com/inventaire/inventaire-client/tree/master/app/modules/entities/scss/_edition_li.scss#L33), without knowing impact evaluation on other browsers

**Comment by maxlath** [comment]
it was also failing on my Chromium, it could be that you had an old version of the app in Chromium cache as that *** browser seems to fail to respect directives to never cache `index.html`.
Removing `flex: 1 0 0; overflow: hidden;` on small screens did the trick.
The patch is in prod if you want to confirm that the issue is solved
