### ISSUE TITLE
Cannot read property "type" of undefined

### ISSUE THREAD

**Issue by Booteille** [inventaire/inventaire-client#183]
After I scanned a book using the protocol EAN_13, I get this error while trying to add it to my inventory:

`Cannot read property "type" of undefined`

Here is a screenshot:
![Screenshot_2019-09-28 menu - Inventaire(1)](https://user-images.githubusercontent.com/2203721/65815367-eca1bf00-e1ee-11e9-82cf-8801d9118370.png)

**Comment by Booteille** [comment]
I just noticed the scan didn't get the good ISBN.
The real one is `9782290173411` and it got me `9782290482223`.

**Comment by maxlath** [comment]
the `Cannot read property "type" of undefined` error should have been fixed by https://github.com/inventaire/inventaire//commit/eebbbb3 but the server shows requests that get `400 entity not found` responses when trying to create items from non-existing entities, and I don't get how that is happening, what part of the client interface offers to create an item from a non-existing entity?

**Comment by Booteille** [comment]
I was just trying to add a book using the integrated scanner.
I scanned my book and got a wrong ISBN from the scanner. So the book added didn't exist.

**Comment by maxlath** [comment]
fixed by #312
