### ISSUE TITLE
Possibility to edit illustrators

### ISSUE THREAD

**Issue by thewholelifetolearn** [inventaire/inventaire-client#202]
As of inventaire/inventaire#252, illustrators are linked to works.
At the moment, it is possible to see them when a work is displayed, but they can't be modified. As a side effect, many illustrators are designed as authors.

So it would be great to have the possibility to edit those information as well.

**Comment by maxlath** [comment]
yes, I was thinking about that too: we could add illustrators (P110), but also colorists (P6338). Do you think it's ok to keep scenarist as authors (P50)?

My only concerns there are:
* the multiplication of patches: one patch to remove the P50 value, one to re-add that value as P110. It would be great if we could make both operations in a single patch
* we probably need a new gadget for that, to move a claim from one property to another easily, and, indeed, in a single patch

**Comment by thewholelifetolearn** [comment]
It depends about Inventaire's philosophy to be (or not) a mirror of Wikidata database. If it is not the case, we can make the "shortcut" that a scenarist is an author too.

In the case of illustrators (and maybe colorists too), I have realized that this information is at the right place in Wikidata for the series. So it may be possible for works that are attached to a series to check if an author is listed as an illustrator is the series or not. If it is the case, then move the author as an illustrator.

In a long term, it would be good to have a functionality to move a property's value to another.

**Comment by aazae** [comment]
Hi,

Linked to this issue, the cleanup tool for advanced users is mileading : 
![image](https://user-images.githubusercontent.com/88883564/143769385-cf5a631a-0643-4ddf-823f-ed26f64f3215.png)

If a series of work have the proper authors /illustrators / colorists property in wikidata, it is well displayed in the series view. However, in the cleanup tool, every illustrators and colorists are seen as "authors", and there is a prompt to add the missing authors in the individual works of the series.
The problem is that it add them as authors wrongly when doing so.

It should either :
- Not show them as authors in this view
- Add them with their correct properties in the individual works

(thx for this project, I love it :) )
