### ISSUE TITLE
inventory view can not load without context

### ISSUE THREAD

**Issue by jum-s** [inventaire/inventaire-client#236]
When visiting an edition page (from an external link for example), i click on user who has an item of this book
Then, on the item's page, when I click on user avatar to go to their inventory
It should display the user inventory view

but instead `this` do not have `itemsList` nor `shelvesList` defined 

![2020-11-11_11-49](https://user-images.githubusercontent.com/5363918/98802859-d3b49700-240b-11eb-8f05-58da8541f6ba.png)

`this` looks like : 

![2020-11-11_11-56](https://user-images.githubusercontent.com/5363918/98803374-8d136c80-240c-11eb-9872-3e99a66211ff.png)

**Comment by jum-s** [comment]
related bug: 

when i open someones item **in a new tab**, then i click on one of the authors of this edition, i expect to be on the author's page but instead i am redirected to the user inventory's page.

**Comment by maxlath** [comment]
the problem seems to be due to the fact that `InventoryLayout` is initialized and rendered twice, so when the first initialized view gets to `startFromUser` and `showUserShelves` internal callbacks, the regions those functions try to access have already been destroyed: it can be fixed by adding `.then(this.ifViewIsIntact('_showUserShelves'))` kind of checks, but it would be better to see why the view is initialized twice

**Comment by maxlath** [comment]
the issue should have been fixed by 0d1afdf, which is now in prod: can you confirm?

**Comment by jum-s** [comment]
nice !
