### ISSUE TITLE
add an introductive modal before opening a wikidata link to edit the data

### ISSUE THREAD

**Issue by maxlath** [inventaire/inventaire-client#29]
currently, infoxbox have a pen icon to signal that the data can be edited:
![infobox](https://cloud.githubusercontent.com/assets/1596934/9498988/efbda616-4c1c-11e5-96a5-3f99f58d5a6b.png)
but clicking the pen opens a wikidata entity page without any explanation of what it is or anything: it could make contributions way more likely if first time clickers where having a modal on inventaire explaining in a few non-experts words what is wikidata and how to add or edit a statement, before being thrown at wikidata

@frimelle , do you know an introduction tutorial for wikidata that we could take inspiration from?

**Comment by frimelle** [comment]
There is the interactive tutorial for new editors on Wikidata: https://www.wikidata.org/wiki/Wikidata:Tours
But that might not be helpful in this case, since we just want them add new fields and ideally not doing a whole tutorial, right? 
So some kind of text wrapping up what Wikidata is and how to edit it is what you are actually looking for here?
