### ISSUE TITLE
Can't add an editor or serie if doesn't exist

### ISSUE THREAD

**Issue by thewholelifetolearn** [inventaire/inventaire-client#96]
I'am adding all my books in Inventaire.io. I realized that some information are missing like the author of the book, the serie it is part of, the editor who published it but if those information aren't in the database, then I can't add it.

Where must be those information given so that I can add them in the edition's/book's sheet?

**Comment by maxlath** [comment]
authors and series can be added from the work data editor (ex: https://inventaire.io/entity/inv:9cf5fbb9affab552cd4fb77712a074db/edit ), while the editor/publisher, as it's specific editions, can be added from the edition data editor (ex: https://inventaire.io/entity/isbn:9782245852279/edit )

**Comment by thewholelifetolearn** [comment]
I'm not on my computer but for example on the second link (edition form for an edition of "Nocturnes Rouges - T2"), I can't enter the editor "Soleil". The "save" button isn't active. 

I will add screenshots tomorrow with examples for the editor and serie.

**Comment by maxlath** [comment]
Yes, for some properties*, it is required to pick among the suggestions before being able to save. 
Alternatively, if the [entities search engine](https://github.com/inventaire/wikidata-subset-search-engine) doesn't suggest the desired entity, it is now possible to directly enter its URI (`Q3489306` or `wd:Q3489306` or `https://www.wikidata.org/wiki/Q3489306`)
This will:
* check that entity is from the expected type (here `publisher`)
* if yes
  * suggest this entity as a possible value
  * add it to the entity search engine, thus making it searchable by text next time
  
\* properties that aren't whitelisted for auto-creating entities from input: cf `allowEntityCreation` parameter in [app/modules/entities/lib/properties](https://github.com/inventaire/inventaire-client/blob/28d5637bddca29b1a5bef1d7bfda55c38e406690/app/modules/entities/lib/properties.coffee)

**Comment by thewholelifetolearn** [comment]
I didn't understand your solution. If the entity isn't available, then I should enter the URI in the form. In this case, `https://www.wikidata.org/wiki/Q3489306` for the publisher?

If it is the case, that is not a simple solution for common users. That means that they have to know the behinds of Inventaire.io. There should be a simpler way for an user to add the information. It similar to #95 . The common user shouldn't have to struggle to enter information because of internal issues.

**Comment by maxlath** [comment]
That's indeed the goal, but there are steps to get there, and its ok to walk one step at a time ;)

Plus, this is part of the data contribution interfaces, which may be
> built with slightly more expert users in mind

There will always be actions that require a little more knowledge on the internals, and thus are only progressively made available to any user: typical example is the possibility to merge two duplicate entities (book, author, publisher, etc.). This action can only be performed by an admin at the moment, as it could create a real mess if not done right. We should work on making it possible for any users, at least to suggest a merge, but that involves walking many steps (integrating new interfaces guiding a user through the internal knowledge to have in mind before suggesting a merge, building an admin tasks queue, etc.).

**Comment by maxlath** [comment]
So, another way to present it is:

* any user should be able to add values (for instance a publisher) just by typing its name
* if it can't be found that way, non-expert users can't do more, but expert users have this extra possibility to designate in a direct, non-ambiguous way, which existing entity they were looking to add; and if it happen to be an entity of the right type, it will be used to update the search engine so that any user can access it by simply typing its name.

This way to do might look weird, but it's also a way to mimic how the Wikidata editor behaves, which is the # 1 provider of data expert users: making them feel at home is also part of the objectives :)

**Comment by thewholelifetolearn** [comment]
I'm trying to add a publisher for a manga (https://inventaire.io/entity/isbn:9782505060451) that isn't available.  
From my understanding, I should find the publisher (Kana) in wikidata and then submit the identifier (Q2339813). I have tried in the edition form but doesn't seem to work. I tried in the website search engine but that doesn't seem to work too. I have tried with the keyword `Kana`, with its identifier `Q2339813`, the link `https://www.wikidata.org/wiki/Q2339813` but none did add the information in the publisher field.

Could you explain again what are the steps to retrieve the information into Inventaire.io's database?

**Comment by maxlath** [comment]
here the problem comes from https://www.wikidata.org/wiki/Q2339813 that isn't complete/accurate, making the entity type test (based on `P31` values) fail: Kana (`Q2339813`) is said to be an instance of (`P31`) business enterprise (`Q4830453`), while a more precise statement would be to declare it as a publishing company ([`Q2085381`](https://www.wikidata.org/wiki/Q2085381)).

Failing the type test, it is thus [not added to suggestions](https://github.com/inventaire/inventaire-client/blob/7b26868763802880df7cbfa37863e3978a7d4e4b/app/modules/entities/lib/sources/type_search.coffee#L42-L43), letting the suggestion list empty:
![failed-publisher](https://cloud.githubusercontent.com/assets/1596934/25844659/70ca3a8a-34ab-11e7-9b5f-8cb5ebfa5f76.png)

I guess, the improvement to do there is to signal to the user that an entity uri as been detected but that it failed the type test by displaying an alert box below the input (instead of failing silently).

**Comment by thewholelifetolearn** [comment]
I just realised something about the availability of authors, publishers, ...  
As you mention in the wiki (https://wiki.inventaire.io/wiki/Books-data?lang=fr) wikidata has only important data. How does it function if it is a small publisher that is considered irrelevant for wikidata? That means it can be declared in inventaire.io ?

**Comment by maxlath** [comment]
inventaire internal entities (all the entities with a uri looking like `inv:aea555cb4000c73f30e5288af10fd040`) are progressively extended to cover all our needs that aren't already covered by Wikidata itself; so now we have
* works (books, comics, etc.). ex: [`inv:aea555cb4000c73f30e5288af10fc819`](https://inventaire.io/entity/inv:aea555cb4000c73f30e5288af10fc819) ([raw data](https://inventaire.io/api/entities?action=by-uris&uris=inv:aea555cb4000c73f30e5288af10fc819))
* their editions. ex: [`isbn:9782505060451` (alias `inv:aea555cb4000c73f30e5288af10fd040`)](https://inventaire.io/entity/isbn:9782505060451) ([raw data](https://inventaire.io/api/entities?action=by-uris&uris=isbn:9782505060451))
* authors. ex: [`inv:aea555cb4000c73f30e5288af10fc320`](https://inventaire.io/entity/inv:aea555cb4000c73f30e5288af10fc320) ([raw data](https://inventaire.io/api/entities?action=by-uris&uris=inv:aea555cb4000c73f30e5288af10fc320))
* series. ex: [`inv:47fb3bb3cdbe82cef00a18d82e005e3a`](https://inventaire.io/entity/inv:47fb3bb3cdbe82cef00a18d82e005e3a) ([raw data](https://inventaire.io/api/entities?action=by-uris&uris=inv:47fb3bb3cdbe82cef00a18d82e005e3a))

Contrarily to Wikidata, [each type has a set of whitelisted properties](https://github.com/inventaire/inventaire-client/blob/d1d4ec0c14e43e26f144a78fb09291811afdc753/app/lib/shared/properties_per_type.coffee), so creating a new entity type is mostly "simply" about declaring which properties it can have and the associated data constraints. It was not opened yet to publishers entity as I assumed close to all publishing companies have a Wikidata entity, thus we should first focus on linking to those, but if you see cases where Wikidata isn't enough, we can work opening this possibility.

**Comment by jum-s** [comment]
It is now possible to add a publisher which doesnt exists
